spring:
  application:
    name: i9-xiaofang-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /web/**
      serviceId: i9-xiaofang-web
